#!/bin/bash

NCDFLIB=/usr/lib64/gfortran/modules
NCDFINC=/usr/include


gfortran -I$NCDFINC -I $NCDFLIB -lnetcdff -c main_globvar.f90 oneDmgcm_reader.f90 adjoint_1D.f90 main.f90 
gfortran -I$NCDFINC -I $NCDFLIB -lnetcdff main_globvar.o oneDmgcm_reader.o adjoint_1D.o main.o -o run.e

# gfortran  -I$NCDFINC -I $NCDFLIB -lnetcdff -c main_globvar.f90 main.f90  oneDmgcm_reader.f90 
